src/newspro/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from blogs.views import Dashboard, category_create, category_list, category_update, category_delete, category_detail
from tiemchung.views import DashboardView
from django.views.generic import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name='dashboard.html'), name='dashboard'),
    path('admin/', admin.site.urls),
    path('tiemchung/', include('tiemchung.urls', namespace='tiemchung')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

    path('category_create', category_create),
    path('category_list', category_list),
    path('category/<pk>', category_detail),
    path('category_update/<pk>/', category_update),
    path('category_delete/<pk>/', category_delete),
]

src/tiemchung/urls.py
from django.urls import path
from tiemchung.forms import SearchForm
from tiemchung.views import (
    DanCreateView,
    DanDeleteView,
    DanDetailView,
    DanUpdateView,
    DanListView,
    SearchView,
    dan_tiem,
    tiem_create
)

app_name = 'tiemchung'

urlpatterns = [
    path('', DanListView.as_view(), name='dan-list'),
    path('create/', DanCreateView.as_view(), name='dan-create'),
    path('search/', SearchView.as_view(), name='search'),
    path('detail/<pk>', DanDetailView.as_view(), name='dan-detail'),
    path('update/<pk>', DanUpdateView.as_view(), name='dan-update'),
    path('delete/<pk>', DanDeleteView.as_view(), name='dan-delete'),
    path('tiem/<pk>', dan_tiem, name='dan-tiem'),
    path('tiem-create/<pk>', tiem_create, name='tiem-create'),

]

src/tiemchung/models.py
from django.shortcuts import redirect
from django.utils import timezone
from django.db import models
from django.urls import reverse


class Dan(models.Model):
    cccd = models.CharField(max_length=20, unique=True)
    ten = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Dan'

    def __str__(self):
        return self.cccd

    def get_absolute_url(self, *args, **kwargs):
        return reverse('tiemchung:dan-detail', kwargs={'pk': self.pk})


class Vaccine(models.Model):
    title = models.CharField(max_length=50)
    made_in = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = 'Vaccine'

    def __str__(self):
        return self.title


class Tiem(models.Model):
    dan = models.ForeignKey(Dan, on_delete=models.CASCADE)
    ngay_tiem = models.DateTimeField(default=timezone.now)
    noi_tiem = models.CharField(max_length=100)
    vaccine = models.ForeignKey(
        Vaccine, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Tiem'

    def __str__(self):
        return self.dan.cccd

src/tiemchung/forms.py
from django import forms
from django.forms import fields
from .models import Dan, Tiem


class DanForm(forms.Form):
    cccd = forms.CharField(max_length=20, widget=forms.TextInput(attrs={
        'class': 'dan',
        'placeholder': 'Căn cước công dân'
    }))
    ten = forms.CharField(label='Tên', max_length=50)


class DanModelForm(forms.ModelForm):
    class Meta:
        model = Dan
        fields = ['cccd', 'ten']


class SearchForm(forms.Form):
    q = forms.CharField(label="Dan", max_length=50)


class TiemCreateModelForm(forms.ModelForm):
    class Meta:
        model = Tiem
        fields = ['noi_tiem', 'vaccine']

src/tiemchung/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.urls.base import reverse, reverse_lazy
from django.views import generic, View
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import Dan, Tiem
from .forms import DanForm, DanModelForm, SearchForm, TiemCreateModelForm

# CRUD = Create, Read, Update, Delete


class DashboardView(generic.TemplateView):
    template_name = 'dashboard.html'


class DanListView(LoginRequiredMixin, generic.ListView):
    template_name = 'tiemchung/list.html'
    queryset = Dan.objects.all()


class DanDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'tiemchung/detail.html'
    queryset = Dan.objects.all()


class DanCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'tiemchung/create.html'
    form_class = DanModelForm
    queryset = Dan.objects.all()
    success_url = reverse_lazy('tiemchung:dan-list')


class DanUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'tiemchung/update.html'
    form_class = DanModelForm
    queryset = Dan.objects.all()
    success_url = reverse_lazy('tiemchung:dan-list')


class DanDeleteView(LoginRequiredMixin, generic.DeleteView):
    template_name = 'tiemchung/delete.html'
    queryset = Dan.objects.all()
    success_url = reverse_lazy('tiemchung:dan-list')


class SearchView(LoginRequiredMixin, View):
    template_name = 'tiemchung/search.html'
    form_class = SearchForm

    def get(self, request, *args, **kwargs):
        form = self.form_class(request.GET or None)
        q = request.GET.get('q')
        qs = Dan.objects.all()
        if q is not None:
            qs = qs.filter(Q(cccd__icontains=q) | Q(ten__icontains=q))

        context = {
            'form': form,
            'object_list': qs
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        pass


@login_required
def dan_tiem(request, pk):  # tiem_list
    dan = get_object_or_404(Dan, pk=pk)
    qs = Tiem.objects.filter(dan=dan)
    context = {
        'object': dan,
        'object_list': qs
    }
    return render(request, 'tiemchung/dan_tiem.html', context)


@login_required
def tiem_create(request, pk):  # tiem create
    dan = get_object_or_404(Dan, pk=pk)
    form = TiemCreateModelForm(request.POST or None)
    if form.is_valid():
        tiem = form.save(commit=False)
        tiem.dan = dan
        tiem.save()
        return redirect('tiemchung:search')
    context = {
        'object': dan,
        'form': form
    }
    return render(request, 'tiemchung/tiem_create.html', context)

src/tiemchung/templates/tiemchung/create.html
{% extends "base.html" %}
{% block title %}Dan create{% endblock title %}
{% block content %}
<h1>Create:</h1>
{% include 'snippets/form.html' with name="Create" %}

{% endblock content %}

src/tiemchung/templates/tiemchung/dan_tiem.html
{% extends "base.html" %}
{% block title %}Dan detail{% endblock title %}
{% block content %}
<h1>Detail:</h1>
<p>CCCD: {{ object.cccd }}</p>
<p>Ten: {{ object.ten }}</p>
<a class="btn btn-primary" href="{% url 'tiemchung:tiem-create' object.pk %}">Tiem</a>
<hr>
<ul>
{% for tiem in object_list %}
    <li>
        Ngay tiem: {{ tiem.ngay_tiem }} - Noi tiem: {{ tiem.noi_tiem }} - Vaccine: {{ tiem.vaccine.title }}
    </li>
{% empty %}
    <p>Chua tiem</p>
{% endfor %}
</ul>

{% endblock content %}

src/tiemchung/templates/tiemchung/delete.html
{% extends "base.html" %}
{% block title %}Dan delete{% endblock title %}
{% block content %}
<h1>Dan delete:</h1>
<p>CCCD: {{ object.cccd }}</p>
<p>Ten: {{ object.ten }}</p>
<form method="POST"> {% csrf_token %}
    <p>Are your sure to delete?</p>
    <button type="submit" class="btn btn-danger">Delete</button>
    <a class="btn btn-warning" href="{% url 'tiemchung:dan-list' %}">Cancel</a>
</form>
{% endblock content %}

src/tiemchung/templates/tiemchung/detail.html
{% extends "base.html" %}
{% block title %}Dan detail{% endblock title %}
{% block content %}
<h1>Detail:</h1>
<p>CCCD: {{ object.cccd }}</p>
<p>Ten: {{ object.ten }}</p>
<hr>
<a href="{% url 'tiemchung:dan-list' %}">Back to the list</a>
{% endblock content %}

src/tiemchung/templates/tiemchung/list.html
{% extends "base.html" %}
{% block title %}Dan list{% endblock title %}
{% block content %}
<div class="row">
{% for dan in object_list %}
    <div class="col col-3 mb-3">
        <div class="card" style="">
        <div class="card-body">
            <h5 class="card-title"><a href="{% url 'tiemchung:dan-detail' dan.pk %}">{{ dan.ten }}</a></h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ dan.cccd }}</h6>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a href="{% url 'tiemchung:dan-update' dan.pk %}" class="card-link">Update</a>
            <a href="{% url 'tiemchung:dan-delete' dan.pk %}" class="card-link">Delete</a>
        </div>
        </div>
    </div>
{% endfor %}
</div>
{% endblock content %}

src/tiemchung/templates/tiemchung/search.html
{% extends "base.html" %}
{% block title %}Dan Search{% endblock title %}
{% block content %}
<div class="mt-2">
    <form>
        {{ form }}
        <button type="submit">Search</button>
    </form>
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">CCCD</th>
      <th scope="col">Ten</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
    {% for dan in object_list %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ dan.cccd }}</td>
      <td>{{ dan.ten }}</td>
      <td><a href="{% url 'tiemchung:dan-tiem' dan.pk %}">Tiem</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

src/tiemchung/templates/tiemchung/tiem_create.html
{% extends "base.html" %}
{% block title %}Dan create{% endblock title %}
{% block content %}
<h1>Tiem:</h1>
{% include 'snippets/form.html' with name="Tiem" %}

{% endblock content %}

src/tiemchung/templates/tiemchung/update.html
{% extends "base.html" %}
{% block title %}Dan Update{% endblock title %}
{% block content %}
<h1>Update:</h1>
<form method="POST">{% csrf_token %}
    {% comment %} <label for="">CCCD</label>
    <input type="text" name="cccd" value="{{ object.cccd }}">
    <label for="">Tên</label>
    <input type="text" name="ten" value="{{ object.ten }}"> {% endcomment %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
{% endblock content %}