src/accounts/urls.py
# The views used below are normally mapped in the AdminSite instance.
# This URLs file is used to provide a reliable view deployment for test purposes.
# It is also provided as a convenience to those who want to deploy these URLs
# elsewhere.

from django.contrib.auth import views
from django.urls import path, reverse_lazy
from .views import UserListView, UserRegistrationView, UserDetailView, UserUpdateView
app_name = 'accounts'
urlpatterns = [
    path('registration/', UserRegistrationView.as_view(), name='registration'),

    path('user-list/', UserListView.as_view(), name='user_list'),
    path('<int:pk>/user-detail/', UserDetailView.as_view(), name='user_detail'),
    path('<int:pk>/user-update/', UserUpdateView.as_view(), name='user_update'),

    path('login/', views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(template_name='accounts/logged_out.html'), name='logout'),

    path('password_change/', views.PasswordChangeView.as_view(template_name='accounts/password_change_form.html',
                                                              success_url=reverse_lazy('accounts:password_change_done')),
         name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
         name='password_change_done'),

    path('password_reset/', views.PasswordResetView.as_view(
        template_name='accounts/password_reset_form.html',
        email_template_name='accounts/password_reset_email.html',
        success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(
         template_name='accounts/password_reset_confirm.html',
         success_url=reverse_lazy('accounts:password_reset_complete')),
         name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
]

src/newspro/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from blogs.views import Dashboard, category_create, category_list, category_update, category_delete, category_detail
from tiemchung.views import DashboardView
from django.views.generic import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name='dashboard.html'), name='dashboard'),
    path('admin/', admin.site.urls),
    path('tiemchung/', include('tiemchung.urls', namespace='tiemchung')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

    path('category_create', category_create),
    path('category_list', category_list),
    path('category/<pk>', category_detail),
    path('category_update/<pk>/', category_update),
    path('category_delete/<pk>/', category_delete),
]

src/tiemchung/urls.py
from django.urls import path
from tiemchung.forms import SearchForm
from tiemchung.views import (
    DanCreateView,
    DanDeleteView,
    DanDetailView,
    DanUpdateView,
    DanListView,
    SearchView,
    dan_tiem,
    tiem_create
)

app_name = 'tiemchung'

urlpatterns = [
    path('', DanListView.as_view(), name='dan-list'),
    path('create/', DanCreateView.as_view(), name='dan-create'),
    path('search/', SearchView.as_view(), name='search'),
    path('detail/<pk>', DanDetailView.as_view(), name='dan-detail'),
    path('update/<pk>', DanUpdateView.as_view(), name='dan-update'),
    path('delete/<pk>', DanDeleteView.as_view(), name='dan-delete'),
    path('tiem/<pk>', dan_tiem, name='dan-tiem'),
    path('tiem-create/<pk>', tiem_create, name='tiem-create'),

]

src/templates/snippets/form.html
<form method="POST">{% csrf_token %}
    {{ form }}
    <button type="submit">{{ name|default:"Submit" }}</button>
</form>

src/templates/snippets/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'dashboard' %}">TC-Covid</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'tiemchung:dan-list' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tiemchung:dan-create' %}">New</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tiemchung:search' %}">Search</a>
        </li>
        {% if request.user.is_staff %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:user_list' %}">User</a>
        </li>
        {% endif %}
      </ul>
      <ul class="navbar-nav d-flex">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:password_change' %}">Change password</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
        </li>
        {% endif %}
        
      </ul>
      
    </div>
  </div>
</nav>