src/accounts/urls.py
# The views used below are normally mapped in the AdminSite instance.
# This URLs file is used to provide a reliable view deployment for test purposes.
# It is also provided as a convenience to those who want to deploy these URLs
# elsewhere.

from django.contrib.auth import views
from django.urls import path, reverse_lazy
from .views import UserListView, UserRegistrationView, UserDetailView, UserUpdateView
app_name = 'accounts'
urlpatterns = [
    path('registration/', UserRegistrationView.as_view(), name='registration'),

    path('user-list/', UserListView.as_view(), name='user_list'),
    path('<int:pk>/user-detail/', UserDetailView.as_view(), name='user_detail'),
    path('<int:pk>/user-update/', UserUpdateView.as_view(), name='user_update'),

    path('login/', views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(template_name='accounts/logged_out.html'), name='logout'),

    path('password_change/', views.PasswordChangeView.as_view(template_name='accounts/password_change_form.html',
                                                              success_url=reverse_lazy('accounts:password_change_done')),
         name='password_change'),
    path('password_change/done/', views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
         name='password_change_done'),

    path('password_reset/', views.PasswordResetView.as_view(
        template_name='accounts/password_reset_form.html',
        email_template_name='accounts/password_reset_email.html',
        success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(
         template_name='accounts/password_reset_confirm.html',
         success_url=reverse_lazy('accounts:password_reset_complete')),
         name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
]

src/newspro/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from blogs.views import Dashboard, category_create, category_list, category_update, category_delete, category_detail
from tiemchung.views import DashboardView
from django.views.generic import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name='dashboard.html'), name='dashboard'),
    path('admin/', admin.site.urls),
    path('tiemchung/', include('tiemchung.urls', namespace='tiemchung')),
    path('accounts/', include('accounts.urls', namespace='accounts')),

    path('category_create', category_create),
    path('category_list', category_list),
    path('category/<pk>', category_detail),
    path('category_update/<pk>/', category_update),
    path('category_delete/<pk>/', category_delete),
]

src/accounts/models.py
from django.db import models

# Create your models here.

src/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.db import models
from django.forms import fields

User = get_user_model()


class UserRegistrationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['is_active', ]

src/accounts/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
from django.utils.crypto import get_random_string
from django.core.mail import send_mail
from .mixins import LoginAndStaffRequiredMixin
from accounts.forms import UserRegistrationForm, UserUpdateForm

User = get_user_model()


class UserRegistrationView(generic.CreateView):  # Create
    template_name = 'accounts/registration.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy('accounts:login')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.set_password(get_random_string(length=8))
        user.save()
        send_mail(
            subject="Thank you for registration",
            message="We've received your registration. We will test and reply you soon.",
            from_email="admin@email.com",
            recipient_list=[user.email, ]
        )
        return super().form_valid(form)


class UserListView(LoginAndStaffRequiredMixin, generic.ListView):  # Read
    template_name = 'accounts/user_list.html'
    queryset = User.objects.all()  # User.objects.filter(is_active=False)


class UserDetailView(LoginAndStaffRequiredMixin, generic.DetailView):  # Read
    template_name = 'accounts/user_detail.html'
    queryset = User.objects.all()


class UserUpdateView(LoginAndStaffRequiredMixin, generic.UpdateView):
    template_name = 'accounts/user_update.html'
    form_class = UserUpdateForm
    queryset = User.objects.all()
    success_url = reverse_lazy('accounts:user_list')

    def form_valid(self, form):
        user = form.save()
        send_mail(
            subject="Your account was activated",
            message="You can reset password to login.",
            from_email="admin@email.com",
            recipient_list=[user.email, ]
        )
        return super().form_valid(form)

src/accounts/templates/accounts/logged_out.html
{% extends "base.html" %}
{% block title %}Logout{% endblock title %}

{% block content %}

<p>Thanks for spending some quality time with the Web site today.</p>

<p><a href="{% url 'accounts:login' %}">Log in again</a></p>

{% endblock %}

src/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock title %}

{% block content %}
<div class="mt-2">
{% include 'snippets/form.html' with name="Login" %}
<p>Forgot password?<a href="{% url 'accounts:password_reset' %}">Reset your password</a></p>
<p>Don't have account?<a href="{% url 'accounts:registration' %}">Registration</a></p>
</div>
{% endblock %}

src/accounts/templates/accounts/password_change_done.html
{% extends "base.html" %}
{% block title %}Password change done{% endblock title %}
{% block content %}
<h1>Password change successful</h1>
<p>Your password was changed.</p>
{% endblock %}

src/accounts/templates/accounts/password_change_form.html
{% extends "base.html" %}

{% block content %}
<h1>Password change</h1>
<p>Please enter your old password, for security’s sake, and then enter your new password twice so we can verify you typed it in correctly.</p>

{% include 'snippets/form.html' with name="Change password" %}

{% endblock %}

src/accounts/templates/accounts/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Password reset complete{% endblock title %}

{% block content %}

<p>Your password has been set.  You may go ahead and log in now.</p>

<p><a href="{% url 'accounts:login' %}">Log in</a></p>

{% endblock %}

src/accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Password reset confirm{% endblock title %}

{% block content %}
<h1>Enter new password</h1>

<p>Please enter your new password twice so we can verify you typed it in correctly.</p>

{% include 'snippets/form.html' with name="Change password" %}

{% endblock %}

src/accounts/templates/accounts/password_reset_done.html
{% extends "base.html" %}
{% block title %}Password reset done{% endblock title %}
{% block content %}
<h1>Password reset sent</h1>
<p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>

<p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>

{% endblock %}

src/accounts/templates/accounts/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

src/accounts/templates/accounts/password_reset_form.html
{% extends "base.html" %}

{% block content %}
<h1>Password reset</h1>
<p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>

{% include 'snippets/form.html' with name="Reset password" %}

{% endblock %}

src/accounts/templates/accounts/registration.html
{% extends "base.html" %}
{% block title %}User Registration{% endblock title %}

{% block content %}
<div class="mt-2">
{% include 'snippets/form.html' with name="Register" %}

</div>
{% endblock %}

src/accounts/templates/accounts/user_detail.html
{% extends "base.html" %}
{% block title %}User Detail{% endblock title %}

{% block content %}
<div class="mt-2">
    <p>{{ object.username }}</p>
    <p>{{ object.email }}</p>
    <p>{{ object.is_active }}</p>
    <a href="{% url 'accounts:user_update' object.pk %}">Activate</a>
</div>
{% endblock %}

src/accounts/templates/accounts/user_list.html
{% extends "base.html" %}
{% block title %}User List{% endblock title %}

{% block content %}
<div class="mt-2">
<ul>
    {% for user in object_list %}
        <li><a href="{% url 'accounts:user_detail' user.pk %}">{{user}}</a></li>
    {% endfor %}
</ul>

</div>
{% endblock %}

src/accounts/templates/accounts/user_update.html
{% extends "base.html" %}
{% block title %}User Activate{% endblock title %}

{% block content %}
<div class="mt-2">
{% include 'snippets/form.html' with name="Activate" %}

</div>
{% endblock %}